site:
  title: Coleta Inmetro
  # the 404 page and sitemap files only get generated when the url property is set
  url: http://localhost:2020
content:
  sources:
    - url: https://github.com/jcarlospontes/Teste-Documentacao.git
      branches: main

asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
